### ISSUE TITLE
`jax.config.jax_experimental_name_stack` removed in JAX v0.3.25

### ISSUE THREAD

**Issue by alembcke** [deepmind/dm-haiku#565]
After updating JAX to v0.3.25 I get the below error:

```
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 123, in __call__
    init(module, *args, **kwargs)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 421, in wrapped
    if jax.config.jax_experimental_name_stack and module_name:
AttributeError: 'Config' object has no attribute 'jax_experimental_name_stack'
```

According to the changelog for JAX v0.3.25 `jax.config.jax_experimental_name_stack` has been removed:
https://jax.readthedocs.io/en/latest/changelog.html

I will be downgrading my JAX version as a workaround for now, but opening this bug report so that Haiku devs know to update Haiku.

**Comment by arunppsg** [comment]
I too had the same error!

**Comment by alembcke** [comment]
It looks like this was fixed in v0.0.9, so closing this issue.

**Comment by dozicauf** [comment]
> It looks like this was fixed in v0.0.9, so closing this issue.

Hi, could you point out to what you are referring with v0.09, i have been having the same issue and I tried multiple solutions.

**Comment by alembcke** [comment]
Running `pip install --upgrade dm-haiku` should solve the issue for you.  The issue was in Haiku v0.0.9dev and earlier, but was fixed in Haiku v0.0.9.  Upgrading the version in `pip` should fix it.
